// Duty Summary JS - Core
const state = {
    shifts: [],
    shiftId: '',
    shiftsOpen: false,
    items: [],
    searchQuery: '',
    targetReportType: 'zongbao',
    targetStatus: 'selected',
    adminDiscarded: false,
    adminProcessScope: 'unprocessed',
    selected: new Set(),
    pendingImport: null,
    pendingUndoTargets: [],
    importConflicts: [],
    importConflictIndex: 0,
    conflictResolutions: []
};
const elements = {
    shiftList: document.getElementById('summary-shift-list'),
    items: document.getElementById('summary-items'),
    context: document.getElementById('summary-context'),
    comparison: document.getElementById('summary-comparison'),
    importTarget: document.getElementById('summary-import-target'),
    discardButton: document.getElementById('btn-discard-selected'),
    importBar: document.getElementById('summary-import-bar'),
    searchInput: document.getElementById('summary-search-input'),
    searchClear: document.getElementById('summary-search-clear'),
    selectAll: document.getElementById('summary-select-all'),
    viewTabs: [...document.querySelectorAll('[data-summary-view]')],
    processFilter: document.getElementById('summary-process-filter'),
    processTabs: [...document.querySelectorAll('[data-admin-process-scope]')],
    columnTabs: [...document.querySelectorAll('.summary-column-tab')],
    filterLayout: document.getElementById('summary-filter-layout'),
    toast: document.getElementById('toast'),
    layout: document.getElementById('summary-layout'),
    shiftsPanel: document.getElementById('summary-shifts-panel'),
    shiftsToggle: document.getElementById('btn-toggle-shifts'),
    shiftsClose: document.getElementById('summary-shifts-close'),
    conflictModal: document.getElementById('summary-import-conflict-modal'),
    conflictProgress: document.getElementById('summary-conflict-progress'),
    conflictTitle: document.getElementById('summary-conflict-article-title'),
    existingColumn: document.getElementById('summary-existing-column'),
    existingSummary: document.getElementById('summary-existing-summary'),
    existingSource: document.getElementById('summary-existing-source'),
    dutyColumn: document.getElementById('summary-duty-column'),
    dutySummary: document.getElementById('summary-duty-summary'),
    dutySource: document.getElementById('summary-duty-source')
};
const businessTimeZone = 'Asia/Shanghai';
