-- Minimal schema for the Edu News pipeline (local PostgreSQL)
-- Apply with `psql -h localhost -U postgres -d <database> -f database/schema.sql`

begin;

create extension if not exists pgcrypto;

-- Raw articles ingested by the crawler (multi-source)
create table if not exists public.raw_articles (
    token text,
    profile_url text,
    article_id text primary key,
    title text,
    source text,
    publish_time bigint,
    publish_time_iso timestamptz,
    url text,
    summary text,
    comment_count integer,
    digg_count integer,
    content_markdown text,
    detail_fetched_at timestamptz,
    fetched_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists raw_articles_fetched_at_idx
    on public.raw_articles (fetched_at desc);

create index if not exists raw_articles_detail_fetched_idx
    on public.raw_articles (detail_fetched_at desc);

-- ---------------------------------------------------------------------------
-- Summaries generated by the pipeline
-- ---------------------------------------------------------------------------
create table if not exists public.news_summaries (
    article_id text primary key,
    title text,
    source text,
    publish_time bigint,
    publish_time_iso timestamptz,
    url text,
    content_markdown text,
    llm_summary text,
    summary_status text not null default 'pending',
    summary_attempted_at timestamptz,
    summary_fail_count integer not null default 0,
    summary_generated_at timestamptz not null default now(),
    fetched_at timestamptz,
    llm_keywords text[] default '{}'::text[],
    correlation numeric(6,3),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists news_summaries_correlation_idx
    on public.news_summaries (correlation desc nulls last);

create index if not exists news_summaries_summary_generated_idx
    on public.news_summaries (summary_generated_at asc);

create index if not exists news_summaries_status_attempt_idx
    on public.news_summaries (summary_status, summary_attempted_at);


-- ---------------------------------------------------------------------------
-- Export history (Feishu brief batches)
-- ---------------------------------------------------------------------------
create table if not exists public.brief_batches (
    id uuid primary key default gen_random_uuid(),
    report_date date not null,
    sequence_no integer not null default 1,
    generated_at timestamptz not null default now(),
    generated_by text,
    export_payload jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (report_date, sequence_no)
);

create table if not exists public.brief_items (
    id uuid primary key default gen_random_uuid(),
    brief_batch_id uuid not null references public.brief_batches(id) on delete cascade,
    article_id text,

    section text,
    order_index integer not null default 0,
    final_summary text,
    approved_by text,
    approved_at timestamptz,
    metadata jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists brief_items_batch_idx
    on public.brief_items (brief_batch_id);

create index if not exists brief_items_section_idx
    on public.brief_items (section);

-- ---------------------------------------------------------------------------
-- Pipeline run bookkeeping
-- ---------------------------------------------------------------------------
create table if not exists public.pipeline_runs (
    id uuid primary key default gen_random_uuid(),
    run_id text not null unique,
    status text not null,
    trigger_source text,
    plan jsonb not null default '[]'::jsonb,
    started_at timestamptz not null,
    finished_at timestamptz,
    steps_completed integer not null default 0,
    artifacts jsonb,
    error_summary text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.pipeline_run_steps (
    id uuid primary key default gen_random_uuid(),
    run_id text not null references public.pipeline_runs(run_id) on delete cascade,
    order_index integer not null,
    step_name text not null,
    status text not null,
    started_at timestamptz not null,
    finished_at timestamptz not null,
    duration_seconds numeric(12,3),
    error text,
    created_at timestamptz not null default now()
);

create index if not exists pipeline_run_steps_run_id_idx
    on public.pipeline_run_steps (run_id, order_index);

-- ---------------------------------------------------------------------------
-- Trigger to maintain updated_at timestamps
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

drop trigger if exists raw_articles_set_updated_at on public.raw_articles;
create trigger raw_articles_set_updated_at
    before update on public.raw_articles
    for each row execute function public.set_updated_at();

drop trigger if exists news_summaries_set_updated_at on public.news_summaries;
create trigger news_summaries_set_updated_at
    before update on public.news_summaries
    for each row execute function public.set_updated_at();


drop trigger if exists brief_batches_set_updated_at on public.brief_batches;
create trigger brief_batches_set_updated_at
    before update on public.brief_batches
    for each row execute function public.set_updated_at();

drop trigger if exists brief_items_set_updated_at on public.brief_items;
create trigger brief_items_set_updated_at
    before update on public.brief_items
    for each row execute function public.set_updated_at();

drop trigger if exists pipeline_runs_set_updated_at on public.pipeline_runs;
create trigger pipeline_runs_set_updated_at
    before update on public.pipeline_runs
    for each row execute function public.set_updated_at();

commit;

