-- Minimal schema for the Edu News pipeline (local PostgreSQL)
-- Apply with `psql -h localhost -U postgres -d <database> -f database/schema.sql`

begin;

create extension if not exists pgcrypto;

-- Raw articles ingested by the crawler (multi-source)
create table if not exists public.raw_articles (
    token text,
    profile_url text,
    article_id text primary key,
    title text,
    source text,
    publish_time bigint,
    publish_time_iso timestamptz,
    url text,
    summary text,
    comment_count integer,
    digg_count integer,
    content_markdown text,
    detail_fetched_at timestamptz,
    fetched_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists raw_articles_fetched_at_idx
    on public.raw_articles (fetched_at desc);

create index if not exists raw_articles_detail_fetched_idx
    on public.raw_articles (detail_fetched_at desc);

-- ---------------------------------------------------------------------------
-- Filtered articles (keyword hits ready for deduplication)
-- ---------------------------------------------------------------------------
create table if not exists public.filtered_articles (
    article_id text primary key,
    keywords text[] not null default '{}'::text[],
    status text not null default 'pending',
    title text,
    source text,
    publish_time bigint,
    publish_time_iso timestamptz,
    url text,
    content_markdown text,
    content_hash text,
    simhash text,
    simhash_bigint bigint,
    simhash_band1 integer,
    simhash_band2 integer,
    simhash_band3 integer,
    simhash_band4 integer,
    primary_article_id text,
    inserted_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint filtered_articles_raw_fk
        foreign key (article_id)
        references public.raw_articles(article_id)
        on delete cascade
);

alter table public.filtered_articles
    add constraint if not exists filtered_articles_primary_fk
        foreign key (primary_article_id)
        references public.filtered_articles(article_id)
        on delete set null
        deferrable initially deferred;

create index if not exists filtered_articles_content_hash_idx
    on public.filtered_articles (content_hash)
    where content_hash is not null;

create index if not exists filtered_articles_status_idx
    on public.filtered_articles (status);

create index if not exists filtered_articles_primary_idx
    on public.filtered_articles (primary_article_id);

create index if not exists filtered_articles_simhash_idx
    on public.filtered_articles (simhash)
    where simhash is not null;

create index if not exists filtered_articles_simhash_band1_idx
    on public.filtered_articles (simhash_band1);

create index if not exists filtered_articles_simhash_band2_idx
    on public.filtered_articles (simhash_band2);

create index if not exists filtered_articles_simhash_band3_idx
    on public.filtered_articles (simhash_band3);

create index if not exists filtered_articles_simhash_band4_idx
    on public.filtered_articles (simhash_band4);

-- ---------------------------------------------------------------------------
-- Primary article staging for scoring and summarization
-- ---------------------------------------------------------------------------
create table if not exists public.primary_articles (
    article_id text primary key,
    primary_article_id text not null,
    status text not null default 'pending',
    score numeric(6,3),
    raw_relevance_score numeric(6,3),
    keyword_bonus_score numeric(6,3),
    score_details jsonb not null default '{}'::jsonb,
    score_updated_at timestamptz,
    title text,
    source text,
    publish_time bigint,
    publish_time_iso timestamptz,
    url text,
    content_markdown text,
    keywords text[] not null default '{}'::text[],
    content_hash text,
    simhash text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint primary_articles_filtered_fk
        foreign key (article_id)
        references public.filtered_articles(article_id)
        on delete cascade,
    constraint primary_articles_primary_fk
        foreign key (primary_article_id)
        references public.filtered_articles(article_id)
        on delete restrict
        deferrable initially deferred
);

create index if not exists primary_articles_status_idx
    on public.primary_articles (status);

create index if not exists primary_articles_primary_idx
    on public.primary_articles (primary_article_id);

create index if not exists primary_articles_score_idx
    on public.primary_articles (score desc nulls last);

-- ---------------------------------------------------------------------------
-- Summaries generated by the pipeline
-- ---------------------------------------------------------------------------
create table if not exists public.news_summaries (
    article_id text primary key,
    title text,
    source text,
    publish_time bigint,
    publish_time_iso timestamptz,
    url text,
    content_markdown text,
    llm_summary text,
    llm_source text,
    score numeric(6,3),
    raw_relevance_score numeric(6,3),
    keyword_bonus_score numeric(6,3),
    score_details jsonb not null default '{}'::jsonb,
    status text not null default 'pending',
    summary_status text not null default 'pending',
    summary_attempted_at timestamptz,
    summary_fail_count integer not null default 0,
    summary_generated_at timestamptz not null default now(),
    fetched_at timestamptz,
    llm_keywords text[] default '{}'::text[],
    is_beijing_related boolean,
    is_beijing_related_llm boolean,
    beijing_gate_checked_at timestamptz,
    beijing_gate_raw jsonb,
    beijing_gate_attempted_at timestamptz,
    beijing_gate_fail_count integer not null default 0,
    sentiment_label text,
    sentiment_confidence double precision,
    external_importance_status text not null default 'pending',
    external_importance_score numeric(6,3),
    external_importance_checked_at timestamptz,
    external_importance_raw jsonb,
    external_filter_attempted_at timestamptz,
    external_filter_fail_count integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


create index if not exists news_summaries_summary_generated_idx
    on public.news_summaries (summary_generated_at asc);

create index if not exists news_summaries_status_attempt_idx
    on public.news_summaries (summary_status, summary_attempted_at);

create index if not exists news_summaries_status_idx
    on public.news_summaries (status);

create index if not exists news_summaries_sentiment_idx
    on public.news_summaries (sentiment_label);

create index if not exists news_summaries_score_idx
    on public.news_summaries (score desc nulls last);

create index if not exists news_summaries_external_filter_idx
    on public.news_summaries (is_beijing_related, sentiment_label, external_importance_status);

create index if not exists news_summaries_beijing_gate_idx
    on public.news_summaries (beijing_gate_attempted_at, summary_generated_at)
    where status = 'pending_beijing_gate' and summary_status = 'completed';

-- ---------------------------------------------------------------------------
-- Manual reviews (decoupled from summaries)
-- ---------------------------------------------------------------------------
create table if not exists public.manual_reviews (
    id uuid primary key default gen_random_uuid(),
    article_id text not null references public.news_summaries(article_id) on delete cascade,
    status text not null check (status in ('pending','selected','backup','discarded','exported')),
    summary text,
    rank double precision,
    notes text,
    score numeric(6,3),
    decided_by text,
    decided_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (article_id)
);

create index if not exists manual_reviews_pending_idx
    on public.manual_reviews (status, rank asc nulls last, article_id)
    where status = 'pending';

create index if not exists manual_reviews_status_idx
    on public.manual_reviews (status);


-- ---------------------------------------------------------------------------
-- Export history (Feishu brief batches)
-- ---------------------------------------------------------------------------
create table if not exists public.brief_batches (
    id uuid primary key default gen_random_uuid(),
    report_date date not null,
    sequence_no integer not null default 1,
    generated_at timestamptz not null default now(),
    generated_by text,
    export_payload jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (report_date, sequence_no)
);

create table if not exists public.brief_items (
    id uuid primary key default gen_random_uuid(),
    brief_batch_id uuid not null references public.brief_batches(id) on delete cascade,
    article_id text,

    section text,
    order_index integer not null default 0,
    final_summary text,
    approved_by text,
    approved_at timestamptz,
    metadata jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists brief_items_batch_idx
    on public.brief_items (brief_batch_id);

create index if not exists brief_items_section_idx
    on public.brief_items (section);

-- ---------------------------------------------------------------------------
-- Pipeline run bookkeeping
-- ---------------------------------------------------------------------------
create table if not exists public.pipeline_runs (
    id uuid primary key default gen_random_uuid(),
    run_id text not null unique,
    status text not null,
    trigger_source text,
    plan jsonb not null default '[]'::jsonb,
    started_at timestamptz not null,
    finished_at timestamptz,
    steps_completed integer not null default 0,
    artifacts jsonb,
    error_summary text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.pipeline_run_steps (
    id uuid primary key default gen_random_uuid(),
    run_id text not null references public.pipeline_runs(run_id) on delete cascade,
    order_index integer not null,
    step_name text not null,
    status text not null,
    started_at timestamptz not null,
    finished_at timestamptz not null,
    duration_seconds numeric(12,3),
    error text,
    created_at timestamptz not null default now()
);

create index if not exists pipeline_run_steps_run_id_idx
    on public.pipeline_run_steps (run_id, order_index);

-- ---------------------------------------------------------------------------
-- Trigger to maintain updated_at timestamps
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

drop trigger if exists raw_articles_set_updated_at on public.raw_articles;
create trigger raw_articles_set_updated_at
    before update on public.raw_articles
    for each row execute function public.set_updated_at();

drop trigger if exists filtered_articles_set_updated_at on public.filtered_articles;
create trigger filtered_articles_set_updated_at
    before update on public.filtered_articles
    for each row execute function public.set_updated_at();

drop trigger if exists primary_articles_set_updated_at on public.primary_articles;
create trigger primary_articles_set_updated_at
    before update on public.primary_articles
    for each row execute function public.set_updated_at();

drop trigger if exists news_summaries_set_updated_at on public.news_summaries;
create trigger news_summaries_set_updated_at
    before update on public.news_summaries
    for each row execute function public.set_updated_at();

comment on column public.news_summaries.is_beijing_related is 'True when the article is related to Beijing; NULL when not evaluated';
comment on column public.news_summaries.is_beijing_related_llm is 'True when the LLM confirms Beijing relevance; NULL when not evaluated';
comment on column public.news_summaries.beijing_gate_checked_at is 'Timestamp when the LLM Beijing gate returned a definitive result';
comment on column public.news_summaries.llm_source is 'Identifier for the LLM model used to generate the summary.';


drop trigger if exists brief_batches_set_updated_at on public.brief_batches;
create trigger brief_batches_set_updated_at
    before update on public.brief_batches
    for each row execute function public.set_updated_at();

drop trigger if exists brief_items_set_updated_at on public.brief_items;
create trigger brief_items_set_updated_at
    before update on public.brief_items
    for each row execute function public.set_updated_at();

drop trigger if exists pipeline_runs_set_updated_at on public.pipeline_runs;
create trigger pipeline_runs_set_updated_at
    before update on public.pipeline_runs
    for each row execute function public.set_updated_at();

commit;
